apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restic-repo
  namespace: backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 50Gi
