---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rest-server-htpasswd
  namespace: backup
spec:
  encryptedData:
    .htpasswd: AgB/OZS8Wp0TPPLr5dXMnce+aes3FOIiMJ3FIm2WUBWjGJiGoIO9c5kNuvh5H9QnBhGa/Lx6x6pbItMbfsMccwd5UINN0TsPIYC8nwyjmICRL1W1jqQIHrx8KgU/r1tQSmW/rHxWR8+oCTJiSE7U2fRB3IHyVMx97RbkqApR/V+j+ZlMX/6tNsUbkaKf8awPDVCLK1+5wLNahGT/VQpvrYTcwerUCeGe6qAHNYQU3O8gb1onLgvvGsaScJnqmq5b24snc+Y4ihydV5ORT+881UXG14G1yHnj+MKQyEH1jSLb1Q2HU4KevQhpuS43QPu3LCUCZjPFTD5BiWDruFtWR8O6DBboWswE4H4U5QAdL+NlF03dgUWxkOmF4SpuD8lXr7CtQNUoMBcgX6QawKPazW3fNCTg1YP9gvLsUY8aFnlU+CS7Cj64pMtQmPCdYGPt9sxI5yKRg4W+egTqymBCMLfms4hEe+lUx3gMyFYin5yS5cArgTspdOVa0jfu4npaFMi0QiEI1Xd9Mfxqrpv7ibvB6V5MIuT2GCCU1WqFYfnUyVM0V3hxZnSy4N60yi9p4qcqSeo6999S7jatHWsl5jUiS4UrpPShrTcDUHIMfHAkPc9FkI//N73ohmmS6W8tr7gf064Zfh1ao0nByXe1ZDYbDVJMr9Ho4ai9FoqXHIgavo7XwcFUXXZADvtpKZV+OY1CMTqj6L3DQDXPGsUFeE/jXciPYTAV0aX43DRXuihbXNdSCByoZ94ySAkayIeU5ObLFZuIMLsjoswse+HLDuWZyxdJ9g==
  template:
    metadata:
      name: rest-server-htpasswd
      namespace: backup
