apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-home
  namespace: kube-system
spec:
  secretName: wildcard-home-tls
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - home
    - jellyfin.home
    - navidrome.home
    - radarr.home
    - sonarr.home
    - prowlarr.home
    - qbittorrent.home
    - argocd.home
    - immich.home
    - actual.home
    - adguard.home
    - auth.home
    - jellyfin.lan.home
    - navidrome.lan.home
    - radarr.lan.home
    - sonarr.lan.home
    - prowlarr.lan.home
    - qbittorrent.lan.home
    - argocd.lan.home
    - immich.lan.home
    - actual.lan.home
    - adguard.lan.home
    - auth.lan.home
  issuerRef:
    name: home-ca
    kind: ClusterIssuer
    group: cert-manager.io
