apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgCpxnVbwuLcnGpUlgWkHAgVpgiZpmc50wGY+pwmi/x4FkMaxhwAJsR4Qly8MMYj2D9H+PXgSBrqMPLApFrkjd0ESDIXyCEodA6siWx+CawVvMMhOJTyjj7HROvHcg5q/jAQ15PTXhLcC3IbZzu8vKWpZvBiLSLzs8pzxm1bN2F/Qs3jZEMtodbGu5XsQwUHbq/Ktbe/dAdA+isFieGzMhqhEHVN4ZeKszMBCa2z9sYt9R2hpU81PQTnm1f97orJsX6oL0GnW3L++rY5MrPtT5yDZqd6R0WJIBdKk1YX5vOWAP+wIpVwmoEAAqe7ZIzrs1TMG030u78qKCk+A4YRG8OrVAYyECXyexVGtvvJugtduMQhERKM0mtaoT1ERgKTG9E23tNbtjk5MyFPo1V4ukf5Akr2nQGRcRKo4PyHb0vjEKO2R8q3nnLr5O+RbLUbuzY7nKjQ3c6nObH6aExMcsNLoX1Sn6WLOLexlXZSS9Ns9Nd/eNRDnXS6MuTu0kEiV6RATZBKc63DpTMxhoHa5+P/PS/MT66psnHv25sluDCx3zT3a/8ucPRL/bgRCjZTJPKK+vXlz1eO8ZuZuvwHN7MgxRPUoocBXxQ1/vwNiuJeZMX4QZJLgWhTnMRyxlSglgEQOsOaVQ2J4t7v9OzAOa7wmERTGBNVT87HUoBiQmXKPDpVIWbZzieEAn/qfRIiHfQiYzUFHxDNnJ7G4BHQfcojHLJGPD7ybK81IKdu9GVUemGvPh9wkG0dsN445iZwiuo/TTa+5LfN/sREBQWAb+Cs
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
