apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  namespace: music
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: music-authentik-forwardauth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts: ["navidrome.lan.home"]
  rules:
    - host: navidrome.lan.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  number: 4533
