apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-argocd.yaml
  - ingress-jellyfin.yaml
  - ingress-navidrome.yaml
  - ingress-radarr.yaml
  - ingress-sonarr.yaml
  - ingress-prowlarr.yaml
  - ingress-qbittorrent.yaml
  - ingress-immich.yaml
  - ingress-actual.yaml
  - ingress-authentik.yaml
  - ingress-adguard.yaml
  - middleware-forwardauth.yaml
